version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-app
    ports:
      - "3001:3000"
    volumes:
      - ./public:/app/public
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - default
      - nginx-proxy-manager_default

networks:
  default:
  nginx-proxy-manager_default:
    external: true
